sudo: required
dist: trusty
language: node_js
os:
  - linux
node_js:
  - "8"
addons:
  apt:
    packages:
      - google-chrome-stable
before_install:
  - node --version
  - npm --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install --user codecov
script:
  # Run linting and unit tests
  - npm run cibuild-travis
  # Create distribution bundles
  - npm run build
